### PR TITLE
Added MappedDoctrineWriter

### PR DESCRIPTION
**Pull request by pulse00**
# Overview

Added a `MappedDoctrineWriter`  which allows to map input item fields to database fields. Use case is when importing an CSV file from some 3rd party which contains different fields than your entities.

Currently only a XML driver is implemented.

Simply add the `csvfield` metadata node to your schema file:

``` XML

   <!--  xmlns:ddeboer="https://github.com/ddeboer/DdeboerDataImportBundle" -->

    <field name="deliveryStatus" type="integer" column="delivery_status">
        <ddeboer:csvfield name="SomeOtherStatus"/>    
    </field>

```

When importing a CSV file, the values in the `SomeOtherStatus` field will be automatically set to the `deliveryStatus` field of the entity.
# Modifications 
- Moved the update logic in `DoctrineWriter` to a dedicated `updateItem` method to ease overriding.
# Tests
- As my local phpunit installation is currently broken after a php 5.4 upgrade, i'm unable to run tests ... However, the [built in](http://travis-ci.org/#!/pulse00/DdeboerDataImportBundle) tests all pass.

### CODE REVIEW

**Comment by pulse00** [comment]
@ddeboer ping

**Comment by pulse00** [comment]
@ddeboer any feedback on this PR? i'll need to maintain a fork otherwise.

**Comment by ddeboer** [comment]
Hey Robert, thanks for your PR. I really like the idea of mapping fields in XML. 

However, I think the proper place to implement the mapping of fields is not in the writers, but on the more generic level of the workflow class. That's why I already had a, albeit very simple, mapping mechanism in `Workflow.php`. What if we added the mapping of properties in XML, which your solution allows, to the generic mapper? This would mean, of course, that we can't use a Doctrine-specific solution. It seems your current implementation can only be used with the Doctrine writer; is that correct?

**Comment by pulse00** [comment]
@ddeboer yeah, that's right. it's coupled to doctrine at the moment. i didn't realize that the `Workflow` class had a mapping implementation sitting there ;).

i'll see if i can refactor this to a more generic approach.

**Comment by pulse00** [comment]
i'll open a new PR if that's implemented properly.

**Pull request closed without merging**
