### PR TITLE
Filters return the changed item

### PR DESCRIPTION
**Pull request by miguelibero**
This pull request enables filters to return the modified item.

### CODE REVIEW

**Comment by ddeboer** [comment]
Hola Miguel, thanks for your work. Can you please explain how returning the filtered item could be useful? 

The way I see it, _filters_ are used for deciding whether a data item (e.g. a row in a spreadsheet) should be accepted into the import workflow. The filters do not change the data item: we have _converters_ for that.

**Comment by miguelibero** [comment]
Hi David,

maybe I misunderstood the usage of Filters.

The problem I had was that I needed to change multiple fields of an item, and a Converter only changes the value of a given field. For example, I have an item with this data:

```
$item = array(
    'tags.es'  => 'prueba',
    'tags.en'  => 'test'
);
```

And I need to convert it to this:

```
$item = array(
    'tags' => array(
        'es' => 'prueba',
        'en' => 'test'
    )
);
```

**Comment by ddeboer** [comment]
Agreed! That is a very annoying limitation of converters. I still think the functionality you describe should not be built into the filters. We should probably change the converters instead.

The reason that converters currently accept only one field (that is, one element in the `$item` array), is that they are then reusable. See, for instance, the example on https://github.com/ddeboer/DdeboerDataImportBundle, where the `DateTimeConverter` is reused for several fields.

```
$dateTimeConverter = new DateTimeConverter();

// Add converters to the workflow
$workflow->addConverter('twn_datumbeschikking', $dateTimeConverter)
         ->addConverter('twn_datumeind', $dateTimeConverter)
         ->addConverter('datummutatie', $dateTimeConverter)
```

A possible solution is to supply the converters with a second parameter, `$item`.

**Comment by ddeboer** [comment]
Hmm, then there's still the problem of changing the input `$item` (one level deep `tags.es` etc.) to the output `$item` (two levels deep `'tags' => array('es', etc.))`.

**Comment by miguelibero** [comment]
How about adding two methods to `Workflow` like:

```
Workflow::addItemConverter(Converter $converter)
Workflow::addItemConverterClosure(\Closure $closure)
```

And then passing the entire item instead of only the field value to the converters added this way.

**Comment by miguelibero** [comment]
@ddeboer what do you think about the last suggestion? I could fix the pull request to work that way if you are ok with it.

**Comment by ddeboer** [comment]
@miguelibero Sounds like a good idea. You can leave out the `addItemConverterClosure`, as I've removed the closure methods in favour of the new `Callback` classes (6d06981c2ff226c17e6532914d04bbd56d22ba95). Could you create a new PR with the desired functionality? I will then close this one. 

Perhaps we should also change the old `Converter` interface to `ValueConverter`, just to make the distinction between the two converters clearer.

**Pull request closed without merging**
